coverage:
  status:
    project:
      default:
        target: auto
        threshold: 90%
        base: auto
    patch:
      default:
        target: auto
        threshold: 90%
        base: auto

codecov:
  require_ci_to_pass: true
  disable_default_path_fixes: true
